title: ""
name: "IT správa Kamil Sukeník Opava"
title_separator: "  "
remote_theme: "mmistakes/minimal-mistakes"

logo: /assets/images/favicon.png

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

permalink: /:title/

defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: it-style

sidebar:
  nav: "main"

sass:
  sass_dir: _sass
  style: compressed









